config/routes.rb
Rails.application.routes.draw do
  resources :genres
  resources :books

  root "books#home"

  get "new" => "books#new"

  get "genres" => "genres#index"

  get "index" => "books#index"

  get "generical" => "books#books_by_genre"

  get "by_title" => "books#books_by_title"

  get "home" => "books#home"

  post "new" => "books#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	mount_uploader :image, ImageUploader
###	validate :isbn_length   <-- going in another direction with the ISBN field

	belongs_to :genre, optional: true

	has_many :book_tags
	has_many :tags, through: :book_tags


#	private
#
#	def isbn_length
#		if isbn.length != 10 || isbn.length != 13 || isbn.length != 0
#			errors.add(:isbn, "must be 10 or 13 characters. If there is no ISBN, please leave blank.")
#		end
#	end	
#### ^ screws up anyway ^ ####

end

app/models/book_hashtag.rb
class BookHashtag < ApplicationRecord
	belongs_to :books
	belongs_to :hahstags
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :books
	#validates :name, presence: true

end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
	has_many :books, through: :book_hashtags
	has_many :book_hashtags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :genres

  def genres
  	@genres = Genre.order(:name)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  
  require 'googlebooks'


  include ApplicationHelper

  # GET /books
  # GET /books.json
  def index
    @books = Book.all.order(:created_at)
  end

  def books_by_genre
    @books = Book.where(genre_id: params[:genre_id])
    @genre = Genre.find(params[:genre_id])
  end

  def books_by_title
    books = Book.all
    @books = books.order(title: :asc)
    
  end

  def home
  end

  def create_book

  end


  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
    @genres = Genre.all.order(:name)

    books = GoogleBooks.search(params[:isbn])
    @first_book = books.first

  end

  # GET /books/1/edit
  def edit
    @genres = Genre.all.order(:name)
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:isbn, :title, :author, :publisher, :publication_date, :format, :location, :note, :collectible, :price, :genre_id, :image)
    end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]
  
  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all.order(:name)
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  def books_by_genre
    @books = Book.where(genre_id: params[:genre_id])
    @genre = Genre.find(params[:genre_id])
    
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def genre_finder
		if @genres
			@genres.collect { |g| [ g.name, g.id ] }
		else
			nil
		end
	end

	def genre_display_on_show_page
		if Genre.find_by(id:@book.genre_id) 
           	Genre.find_by(id:@book.genre_id).name
        else
           	nil
        end
    end

    def genre_display_on_index_page(book)
    	if Genre.find_by(id: book.genre_id)
    		Genre.find_by(id: book.genre_id).name
    	else
    		"" # in the modal, nil will return the path
    	end
    end

# everything below is so that the form will still display even if you can't get an isbn to start with

    def google_isbn
        if @first_book
            @first_book.isbn
        else
            nil
        end
    end

    def google_title
        if @first_book
            @first_book.title
        else
            nil
        end
    end

    def google_authors
        if @first_book
            @first_book.authors
        else
            nil
        end
    end

    def google_publisher
        if @first_book
            @first_book.publisher
        else
            nil
        end
    end

    def google_year
        if @first_book
            @first_book.published_date[0..3]
        else
            nil
        end
    end

    def google_image
        if @first_book
            @first_book.image_link(:zoom => 2) # medium
        else
            nil
        end
    end


end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/books/_book_loop.html.erb
<table>
  <thead>
    <tr>
      <th></th>
      <th id="author">Author</th>
      <th>Title</th>
      <th id="publisher">Publisher</th>
      <th id="year">Year</th>
      <th>Genre</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <div class="modal fade" id="myModal_<%= book.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
              </div>
              <div class="modal-body">
                <% if book.image.url.nil? == false %>
                  <p><%= image_tag book.image.url, class: "book-pics" %></p>
                <% end %>
                <h3><%= link_to book.title, book %></h3>
                <p><%= book.author %></p>
                <p><%= book.publisher %> <%= book.publication_date %></p>
                <p><%= link_to genre_display_on_index_page(book), generical_path(genre_id: book.genre_id) %> <%= book.format %></p>
                
                <p><strong>Located:</strong><%= book.location %></p>
                <p><strong>Note:</strong></p>
                <p><%= book.note %></p>
                <p><%= number_to_currency book.price %></p>
              </div>
              <div class="modal-footer">
                <p>
          <!-- empty for now -->
                </p>
              </div>
            </div>
          </div>
        </div>
        <td><a href="" data-toggle="modal" data-target="#myModal_<%= book.id %>" > More Info</a></td>
        <td id="author"><%= book.author %></td>
        <td><%= book.title %></td>
        <td id="publisher"><%= book.publisher %></td>
        <td id="year"><%= book.publication_date %></td>
        <td><%= genre_display_on_index_page(book) %>
        <td><%= book.note %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container" id="form-whole">

  
    <div class="form-group top-three">
      <%= form.label :isbn, "ISBN" %>
      <%= form.text_field :isbn, id: :book_isbn, :value => google_isbn, placeholder: "Either the ISBN. For 9 digit SBNs, just add a 0 to the front", class: "form-control" %>
    </div>

    <div class="form-group top-three">
      <%= form.label :title %>
      <%= form.text_field :title, id: :book_title, placeholder: "Enter the title", class: "form-control"%>
    </div>

    <div class="form-group top-three">
      <%= form.label :author %>
      <%= form.text_field :author, id: :book_author, placeholder: "Enter the Author's name (Last Name, First Name)", class: "form-control" %>
    </div>
    



    <div class="publisher-couple">
      <div class="form-group publisher">
        <%= form.label :publisher %>
        <%= form.text_field :publisher, id: :book_publisher, placeholder: "Enter the publisher", class: "form-control" %>
      </div>

      <div class="form-group date">
        <%= form.label :publication_date, "Year Published" %>
        <%= form.text_field :publication_date, id: :book_publication_date, discard_day: :true, discard_month: :true, placeholder: "Enter the publication year", class: "form-control" %>
      </div>
    </div>
  
    
    <div class="genre_and_format">
    
      <div class="genre">
        <%= form.label :genre %>
        <%= form.select :genre_id, genre_finder, {include_blank: "Select Genre" }, class: "genre_dropbox" %>
        <%= link_to "Remove or Add a Genre", genres_path, class: "genre_link" %>

    
      </div> <!-- genre_box -->


      <div class="format">
        <%= form.label :format %>
        <%= form.select :format, options_for_select([["Select Format", ""], "Hardcover", "Trade Paperback", "Paperback", "Book Club", "Other"]), { id: :book_format }, {class: "format_dropbox" } %>
      </div>
    </div> <!-- genre_and_format -->

    <div class="form-group note">
      <%= form.label :note %>
      <%= form.text_area :note, id: :book_note, placeholder: "Enter any notes on this item", class: "form-control" %>
    </div>
    

    <div class="location_and_collectible">
      <div class="form-group">
        <%= form.label :location %>
        <%= form.text_field :location, id: :book_location, placeholder: "Enter location in your collection", class: "form-control location" %>
      </div>

      <div class="collectible-side">
        <div class="field">
          <%= form.label :collectible, "Collectible" %>
          <%= form.check_box :collectible, id: :book_collectible, class: "check_box" %>
        </div>
      </div> <!-- collectible side -->
    </div>  <!-- location_and_collectible -->


    <!-- COMMENTED OUT COMMENTED OUT COMMENTED OUT -->
    <% if false %> <!-- commented out below -->
    <div class="form-group">
      <%= form.label :tags, "Tags" %>
      <%= form.text_area :tags, id: :book_tags %>
    </div>
    <% end %> <!-- commented out above -->
    <!-- COMMENTED OUT COMMENTED OUT COMMENTED OUT -->

    <div class="bottom_row">
      <div class="price_form">
        <div class="form-group">
          <%= form.label :price %>
          <%= form.text_field :price, id: :book_price, class: "form-control price_field" %>
        </div>
      </div> <!-- price_form -->

      <div class="image_form">
        <div class="form-group">
          <strong>Upload Book Image: </strong>
          <%= form.file_field :image, class: "image" %>
        </div>    
      </div> <!-- image_form -->

    </div>  <!-- bottom row -->





  
</div>

<div class="container">

    <div class="actions">
      <%= form.submit %>
    </div>

    <% end %>
</div>

app/views/books/books_by_genre.html.erb
<h1><%= @genre.name %> Books</h1>

<% provide(:title, @genre.name) %>

<%= render 'book_loop' %>

app/views/books/books_by_title.html.erb
<h1>Books Alphabatized by Title</h1>

<% provide(:title, "Books Alphabatized by Title") %>

<%= render 'book_loop' %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% provide(:title, "Edit an Entry") %>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/home.html.erb
<h1>BOOKFINDER</h1>

<div class="container">
	
	<div class="container front-page">
	    
	    <div class="bar_and_title">
		    <h3 id="home_title">ENTER AN ISBN</h3>
		    
		    <%= form_tag new_path do %>
			<%= text_field_tag :isbn, nil, placeholder: "ISBN", class: "form-control bar" %><br />
		        <%= submit_tag "Submit Book", class: "first-button" %>
		    <% end %>
		</div>
		    
	</div>
</div>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<% provide(:title, "All Books") %>

<h1>All Books</h1>

<%= render 'book_loop' %>

app/views/books/new.html.erb
<% provide(:title, "Enter a New Book") %>




<%= form_with(model: @book, local: true) do |form| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container" id="form-whole">

    <h1>New Book</h1>
    <br>
  
    <div class="form-group top-three">
      <%= form.label :isbn, "ISBN" %>
      <%= form.text_field :isbn, id: :book_isbn, :value => google_isbn, placeholder: "Either the ISBN. For 9 digit SBNs, just add a 0 to the front", class: "form-control" %>
    </div>

    <div class="form-group top-three">
      <%= form.label :title %>
      <%= form.text_field :title, id: :book_title, :value => google_title, placeholder: "Enter the title", class: "form-control"%>
    </div>

    <div class="form-group top-three">
      <%= form.label :author %>
      <%= form.text_field :author, id: :book_author, :value => google_authors, placeholder: "Enter the Author's name (Last Name, First Name)", class: "form-control" %>
    </div>
    



    <div class="publisher-couple">
      
      <div class="form-group publisher">
        <%= form.label :publisher %>
        <%= form.text_field :publisher, id: :book_publisher, :value => google_publisher, placeholder: "Enter the publisher", class: "form-control" %>
      </div>

      <div class="form-group date">
        <%= form.label :publication_date, "Year Published" %>
        <%= form.text_field :publication_date, id: :book_publication_date, :value => google_year, discard_day: :true, discard_month: :true, placeholder: "Enter the publication year", class: "form-control" %>
      </div>
    </div>
  
    
    <div class="genre_and_format">
    
      <div class="genre">
        <%= form.label :genre %>
        <%= form.select :genre_id, genre_finder, {include_blank: "Select Genre" }, class: "genre_dropbox" %>
        <%= link_to "Remove or Add a Genre", genres_path, class: "genre_link" %>

    
      </div> <!-- genre_box -->


      <div class="format">
        <%= form.label :format %>
        <%= form.select :format, options_for_select([["Select Format", ""], "Hardcover", "Trade Paperback", "Paperback", "Book Club", "Other"]), { id: :book_format }, {class: "format_dropbox" } %>
      </div>
    </div> <!-- genre_and_format -->

    <div class="form-group note">
      <%= form.label :note %>
      <%= form.text_area :note, id: :book_note, placeholder: "Enter any notes on this item", class: "form-control" %>
    </div>
    

    <div class="location_and_collectible">
      <div class="form-group">
        <%= form.label :location %>
        <%= form.text_field :location, id: :book_location, placeholder: "Enter location in your collection", class: "form-control location" %>
      </div>

      <div class="collectible-side">
        <div class="field">
          <%= form.label :collectible, "Collectible" %>
          <%= form.check_box :collectible, id: :book_collectible, class: "check_box" %>
        </div>
      </div> <!-- collectible side -->
    </div>  <!-- location_and_collectible -->


    <!-- COMMENTED OUT COMMENTED OUT COMMENTED OUT -->
    <% if false %> <!-- commented out below -->
    <div class="form-group">
      <%= form.label :tags, "Tags" %>
      <%= form.text_area :tags, id: :book_tags %>
    </div>
    <% end %> <!-- commented out above -->
    <!-- COMMENTED OUT COMMENTED OUT COMMENTED OUT -->

    <div class="bottom_row">
      <div class="price_form">
        <div class="form-group">
          <%= form.label :price %>
          <%= form.text_field :price, id: :book_price, class: "form-control price_field" %>
        </div>
      </div> <!-- price_form -->

      <div class="image_form">
        <div class="form-group">
          <strong>Upload Book Image: </strong>
          <%= form.file_field :image, :value => google_image, class: "image" %>
        </div>    
      </div> <!-- image_form -->

    </div>  <!-- bottom row -->





  
</div>

<div class="container">

    <div class="action">
      <%= form.submit %>
    </div>

    <% end %>
</div>


<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ISBN:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @book.publisher %>
</p>

<p>
  <strong>Publication date:</strong>
  <%= @book.publication_date %>
</p>

<p>
  <strong>Format:</strong>
  <%= @book.format %>
</p>

<p>
  <strong>Location:</strong>
  <%= @book.location %>
</p>

<p>
  <strong>Note:</strong>
  <%= @book.note %>
</p>

<p>
  <strong>Collectible:</strong>
  <%= @book.collectible ? "Yes" : "No" %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>


<!-- the rails way of commenting out, apparently -->
<% if false %>
<!-- <p>
  <strong>Tags:</strong>
  <%= @book.tags %>
</p> -->
<% end %>
<!-- end -->


<p>
  <strong>Genre:</strong>
  <%= genre_display_on_show_page %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/genres/_form.html.erb
<%= form_with(model: genre, local: true) do |form| %>
  <% if genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :genre_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<h1>Editing Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/genres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Genres</h1>

<div container="genre-container">
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @genres.each do |genre| %>
        <tr>
          <td><%= genre.name %></td>
          <td><%= link_to 'Edit', edit_genre_path(genre) %></td>
          <td><%= link_to 'Destroy', genre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Genre', new_genre_path %>
</div> 

app/views/genres/new.html.erb
<h1>New Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Back', genres_path %>

app/views/genres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @genre.name %>
</p>

<%= link_to 'Edit', edit_genre_path(@genre) %> |
<%= link_to 'Back', genres_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Home", root_path, class: "navbar-brand" %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">


<!-- begin categories -->

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Genres <span class="caret"></span></a>
          <ul class="dropdown-menu">
              <% @genres.each do |genre| %>
              <li><%= link_to genre.name, generical_path(genre_id: genre.id) %></li>
              <% end %>
            </ul>
          </li>  
        

<!-- end categories -->

<!-- begin brands -->


<!-- end brands --> 



		</ul>
	</div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Book Catalogger</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<nav class="navbar navbar-default">
  		<div class="container-fluid">
  		   	<!-- Brand and toggle get grouped for better mobile display -->	
  		   	<div class="navbar-header">
  		   		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          			<span class="sr-only">Toggle navigation</span>
          			<span class="icon-bar"></span>
          			<span class="icon-bar"></span>
          			<span class="icon-bar"></span>
        		</button>
        		<%= link_to "Home", root_path, class: "navbar-brand" %>  	
  		   	</div> <!-- for navbar-header -->

  		   	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        		<ul class="nav navbar-nav">
 

        		<!-- BEGIN GENRES -->	
        				
  					<li class="dropdown">
  						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Genres <span class="caret"></span></a>
  						<ul class="dropdown-menu">
  							<% @genres.each do |genre| %>
              				<li><%= link_to genre.name, generical_path(genre_id: genre.id) %></li>
              				<% end %>
  						</ul> <!-- for dropdown-menu -->
  					</li> <!-- li class dropdown -->

  				<!-- END GENRES -->

  				<!-- ANOTHER DROPDOWN FOR TITLES N SHIT -->
  				<!-- END DROPDOWN -->


  				</ul> <!-- for ul class navbar -->
  			</div> <!-- for NAVBAR COLLAPSE? -->

  		</div> <!-- for container-fluid -->
  	</nav>	<!-- for navbar -->

  	<div class="container">
    	<%= yield %>
    </div>	

  </body>
</html>